SELECT INSTNM,CITY,STABBR,ACCREDAGENCY FROM school LIMIT 10;

SELECT INSTNM,CITY,STABBR,ACCREDAGENCY FROM school 
WHERE STABBR IN ("NJ","PA","DE") LIMIT 10;

SELECT INSTNM,CITY,STABBR,ACCREDAGENCY FROM school 
WHERE CITY = "Philadelphia"
ORDER BY INSTNM
LIMIT 10;

SELECT INSTNM FROM school 
WHERE STABBR IN ("NJ","PA","DE") 
AND DISTANCEONLY = 1
ORDER BY INSTNM
LIMIT 10;

SELECT INSTNM,CITY,STABBR FROM school
WHERE INSTURL NOT LIKE "%.edu%"
AND DISTANCEONLY = 1; 

SELECT INSTNM,CITY,STABBR,ACCREDAGENCY,DISTANCEONLY FROM school
WHERE STABBR = "PA"
AND (ACCREDAGENCY LIKE "%vocation%" 
	OR ACCREDAGENCY LIKE "%career%") 
ORDER BY INSTNM; 

SELECT DISTINCT ACCREDAGENCY FROM school
WHERE STABBR = "PA"
AND ACCREDAGENCY NOT LIKE "%Middle States Commission%";

